/* /api/Status
GET Request liefert Array an Bot Status Objekten
Datenverwendung fuer Status Tabelle
*/
var response = [{
id: 0,
ip: '127.0.0.1',
task: 1,
workload: 0.0 // 0.0 means inactive, 1.0 means too much to do
}];

/*
/api/Status
POST Request akzeptiert status Flag
Verwendung fuer Toggle Button
*/
// enables Bot #0
var data = {
id: 0,
status: true
};

/* /api/Tasks
GET Request liefert Array an Auftrag Objekten
Verwendung fuer Tasks Tabelle
*/
var response = [{
id: 0,
type: 'hash-md5',
data: {
input: 'woot',
output: null // Not computed yet, String if computed
}
}];

/*
/api/Tasks
POST Request akzeptiert Datenobjekt ohne ID
Verwendung fuer Tasks Formular
*/
var data = {
type: 'hash-md5',
data: {
input: 'woot' // output is generated by Bots
}
};
